spring:
  profiles:
    active: ${profiles_active:local}
  output:
    ansi:
      enabled: always
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    problemdetails:
      enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

